// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module IFU(	// @[src/main/IFU.scala:10:7]
  input         clock,	// @[src/main/IFU.scala:10:7]
                reset,	// @[src/main/IFU.scala:10:7]
  output [31:0] io_mem_addr,	// @[src/main/IFU.scala:11:14]
  output        io_mem_reqValid,	// @[src/main/IFU.scala:11:14]
  input  [31:0] io_mem_rdata,	// @[src/main/IFU.scala:11:14]
  input         io_mem_respValid,	// @[src/main/IFU.scala:11:14]
  output        io_out_valid,	// @[src/main/IFU.scala:11:14]
  output [31:0] io_out_bits_inst,	// @[src/main/IFU.scala:11:14]
                io_out_bits_snpc,	// @[src/main/IFU.scala:11:14]
  input         io_redirect_valid,	// @[src/main/IFU.scala:11:14]
  input  [31:0] io_redirect_dnpc,	// @[src/main/IFU.scala:11:14]
  input         io_nextInst	// @[src/main/IFU.scala:11:14]
);

  reg  [31:0] PC;	// @[src/main/IFU.scala:17:19]
  wire [31:0] _snpc_T = PC + 32'h4;	// @[src/main/IFU.scala:17:19, :18:17]
  reg         fetchInst_REG;	// @[src/main/IFU.scala:22:49]
  reg         fetchInst;	// @[src/main/IFU.scala:22:26]
  reg         state;	// @[src/main/IFU.scala:28:22]
  reg  [31:0] io_out_bits_inst_r;	// @[src/main/IFU.scala:37:68]
  always @(posedge clock) begin	// @[src/main/IFU.scala:10:7]
    if (reset) begin	// @[src/main/IFU.scala:10:7]
      PC <= 32'h30000000;	// @[src/main/IFU.scala:17:19]
      fetchInst_REG <= 1'h1;	// @[src/main/IFU.scala:22:49]
      fetchInst <= 1'h0;	// @[src/main/IFU.scala:22:26]
      state <= 1'h0;	// @[src/main/IFU.scala:28:22]
    end
    else begin	// @[src/main/IFU.scala:10:7]
      if (io_nextInst)	// @[src/main/IFU.scala:11:14]
        PC <= {io_redirect_valid ? io_redirect_dnpc[31:2] : _snpc_T[31:2], 2'h0};	// @[src/main/IFU.scala:7:40, :10:7, :11:14, :17:19, :18:17, :20:19]
      fetchInst_REG <= 1'h0;	// @[src/main/IFU.scala:22:49]
      fetchInst <= io_nextInst | fetchInst_REG;	// @[src/main/IFU.scala:22:{26,39,49}]
      state <= ~state & fetchInst | state & ~io_mem_respValid;	// @[src/main/IFU.scala:22:26, :28:22, :31:33, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
    end
    if (io_mem_respValid)	// @[src/main/IFU.scala:11:14]
      io_out_bits_inst_r <= io_mem_rdata;	// @[src/main/IFU.scala:37:68]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/IFU.scala:10:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/IFU.scala:10:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/IFU.scala:10:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[src/main/IFU.scala:10:7]
    initial begin	// @[src/main/IFU.scala:10:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/IFU.scala:10:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/IFU.scala:10:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/IFU.scala:10:7]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/IFU.scala:10:7]
        end	// @[src/main/IFU.scala:10:7]
        PC = _RANDOM[2'h0];	// @[src/main/IFU.scala:10:7, :17:19]
        fetchInst_REG = _RANDOM[2'h1][0];	// @[src/main/IFU.scala:10:7, :22:49]
        fetchInst = _RANDOM[2'h1][1];	// @[src/main/IFU.scala:10:7, :22:{26,49}]
        state = _RANDOM[2'h1][2];	// @[src/main/IFU.scala:10:7, :22:49, :28:22]
        io_out_bits_inst_r = {_RANDOM[2'h1][31:3], _RANDOM[2'h2][2:0]};	// @[src/main/IFU.scala:10:7, :22:49, :37:68]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/IFU.scala:10:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/IFU.scala:10:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_mem_addr = {PC[31:2], 2'h0};	// @[src/main/IFU.scala:7:{25,40}, :10:7, :17:19]
  assign io_mem_reqValid = fetchInst & ~state;	// @[src/main/IFU.scala:10:7, :22:26, :28:22, :34:32, src/main/utils/Utils.scala:21:92]
  assign io_out_valid = io_mem_respValid;	// @[src/main/IFU.scala:10:7]
  assign io_out_bits_inst = io_mem_respValid ? io_mem_rdata : io_out_bits_inst_r;	// @[src/main/IFU.scala:10:7, :37:{26,68}]
  assign io_out_bits_snpc = _snpc_T;	// @[src/main/IFU.scala:10:7, :18:17]
endmodule

module IDU(	// @[src/main/IDU.scala:6:7]
  input         clock,	// @[src/main/IDU.scala:6:7]
                reset,	// @[src/main/IDU.scala:6:7]
                io_in_valid,	// @[src/main/IDU.scala:7:14]
  input  [31:0] io_in_bits_inst,	// @[src/main/IDU.scala:7:14]
                io_in_bits_snpc,	// @[src/main/IDU.scala:7:14]
  output        io_out_valid,	// @[src/main/IDU.scala:7:14]
  output [31:0] io_out_bits_src1,	// @[src/main/IDU.scala:7:14]
                io_out_bits_src2,	// @[src/main/IDU.scala:7:14]
                io_out_bits_src3,	// @[src/main/IDU.scala:7:14]
  output        io_out_bits_wen,	// @[src/main/IDU.scala:7:14]
  output [3:0]  io_out_bits_rd,	// @[src/main/IDU.scala:7:14]
  output [2:0]  io_out_bits_decode_funct3,	// @[src/main/IDU.scala:7:14]
  output        io_out_bits_decode_isLoad,	// @[src/main/IDU.scala:7:14]
                io_out_bits_decode_isStore,	// @[src/main/IDU.scala:7:14]
                io_out_bits_decode_isJmp,	// @[src/main/IDU.scala:7:14]
  output [31:0] io_out_bits_snpc,	// @[src/main/IDU.scala:7:14]
  input  [31:0] io_wb_res,	// @[src/main/IDU.scala:7:14]
  input         io_wb_wen,	// @[src/main/IDU.scala:7:14]
  input  [3:0]  io_wb_rd	// @[src/main/IDU.scala:7:14]
);

  wire [3:0]  io_out_bits_rd_0;	// @[src/main/IDU.scala:43:44, :75:11]
  wire        isUtype = io_in_bits_inst[4:2] == 3'h5;	// @[src/main/IDU.scala:18:{21,28}]
  wire        isJtype = io_in_bits_inst[6:2] == 5'h1B;	// @[src/main/IDU.scala:19:{21,28}]
  wire        isStype = io_in_bits_inst[6:2] == 5'h8;	// @[src/main/IDU.scala:19:21, :20:28]
  wire        isBtype = io_in_bits_inst[6:2] == 5'h18;	// @[src/main/IDU.scala:19:21, :21:28]
  `ifndef SYNTHESIS	// @[src/main/IDU.scala:45:9]
    wire [9:0] _GEN = {io_in_bits_inst[14:12], io_in_bits_inst[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
    always @(posedge clock) begin	// @[src/main/IDU.scala:45:9]
      if (~reset
          & ~(~io_in_valid
              | ~(~(_GEN == 10'h13
                    | {io_in_bits_inst[31:25],
                       io_in_bits_inst[14:12],
                       io_in_bits_inst[6:0]} == 17'h33 | io_in_bits_inst[6:0] == 7'h37
                    | _GEN == 10'h67 | _GEN == 10'h203 | _GEN == 10'h103 | _GEN == 10'h23
                    | _GEN == 10'h123) & io_in_bits_inst != 32'h100073))) begin	// @[src/main/IDU.scala:45:{9,10,23,50}, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
        if (`ASSERT_VERBOSE_COND_)	// @[src/main/IDU.scala:45:9]
          $error("Assertion failed: Invalid instruction 0x%x\n    at IDU.scala:45 assert(!io.in.valid || AllInst.isIllegal(inst) === false.B, \"Invalid instruction 0x%%%%x\", inst)\n",
                 io_in_bits_inst);	// @[src/main/IDU.scala:45:9]
        if (`STOP_COND_)	// @[src/main/IDU.scala:45:9]
          $fatal;	// @[src/main/IDU.scala:45:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  reg  [31:0] R_1;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_2;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_3;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_4;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_5;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_6;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_7;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_8;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_9;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_10;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_11;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_12;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_13;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_14;	// @[src/main/IDU.scala:48:59]
  reg  [31:0] R_15;	// @[src/main/IDU.scala:48:59]
  wire [31:0] rs2Val =
    R_1 & {32{io_in_bits_inst[24:20] == 5'h1}} | R_2
    & {32{io_in_bits_inst[24:20] == 5'h2}} | R_3 & {32{io_in_bits_inst[24:20] == 5'h3}}
    | R_4 & {32{io_in_bits_inst[24:20] == 5'h4}} | R_5
    & {32{io_in_bits_inst[24:20] == 5'h5}} | R_6 & {32{io_in_bits_inst[24:20] == 5'h6}}
    | R_7 & {32{io_in_bits_inst[24:20] == 5'h7}} | R_8
    & {32{io_in_bits_inst[24:20] == 5'h8}} | R_9 & {32{io_in_bits_inst[24:20] == 5'h9}}
    | R_10 & {32{io_in_bits_inst[24:20] == 5'hA}} | R_11
    & {32{io_in_bits_inst[24:20] == 5'hB}} | R_12 & {32{io_in_bits_inst[24:20] == 5'hC}}
    | R_13 & {32{io_in_bits_inst[24:20] == 5'hD}} | R_14
    & {32{io_in_bits_inst[24:20] == 5'hE}} | R_15 & {32{io_in_bits_inst[24:20] == 5'hF}};	// @[src/main/IDU.scala:48:59, :49:{66,72,84,107}, :60:37]
  wire        src2UseReg =
    io_in_bits_inst[6:2] == 5'hC | io_in_bits_inst[6:2] == 5'hE | isBtype;	// @[src/main/IDU.scala:19:21, :21:28, :23:{29,45,60}, :64:28]
  assign io_out_bits_rd_0 = io_in_bits_inst[10:7];	// @[src/main/IDU.scala:43:44, :75:11]
  always @(posedge clock) begin	// @[src/main/IDU.scala:6:7]
    if (io_wb_wen & io_wb_rd == 4'h1)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_1 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'h2)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_2 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'h3)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_3 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'h4)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_4 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'h5)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_5 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'h6)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_6 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'h7)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_7 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'h8)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_8 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'h9)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_9 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'hA)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_10 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'hB)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_11 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'hC)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_12 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'hD)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_13 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & io_wb_rd == 4'hE)	// @[src/main/IDU.scala:6:7, :48:59, :50:{98,107,111}, :78:20]
      R_14 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
    if (io_wb_wen & (&io_wb_rd))	// @[src/main/IDU.scala:48:59, :50:{98,107,111}, :78:20]
      R_15 <= io_wb_res;	// @[src/main/IDU.scala:48:59]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/IDU.scala:6:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/IDU.scala:6:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/IDU.scala:6:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:14];	// @[src/main/IDU.scala:6:7]
    initial begin	// @[src/main/IDU.scala:6:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/IDU.scala:6:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/IDU.scala:6:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/IDU.scala:6:7]
        for (logic [3:0] i = 4'h0; i < 4'hF; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/IDU.scala:6:7]
        end	// @[src/main/IDU.scala:6:7]
        R_1 = _RANDOM[4'h0];	// @[src/main/IDU.scala:6:7, :48:59]
        R_2 = _RANDOM[4'h1];	// @[src/main/IDU.scala:6:7, :48:59]
        R_3 = _RANDOM[4'h2];	// @[src/main/IDU.scala:6:7, :48:59]
        R_4 = _RANDOM[4'h3];	// @[src/main/IDU.scala:6:7, :48:59]
        R_5 = _RANDOM[4'h4];	// @[src/main/IDU.scala:6:7, :48:59]
        R_6 = _RANDOM[4'h5];	// @[src/main/IDU.scala:6:7, :48:59]
        R_7 = _RANDOM[4'h6];	// @[src/main/IDU.scala:6:7, :48:59]
        R_8 = _RANDOM[4'h7];	// @[src/main/IDU.scala:6:7, :48:59]
        R_9 = _RANDOM[4'h8];	// @[src/main/IDU.scala:6:7, :48:59]
        R_10 = _RANDOM[4'h9];	// @[src/main/IDU.scala:6:7, :48:59]
        R_11 = _RANDOM[4'hA];	// @[src/main/IDU.scala:6:7, :48:59]
        R_12 = _RANDOM[4'hB];	// @[src/main/IDU.scala:6:7, :48:59]
        R_13 = _RANDOM[4'hC];	// @[src/main/IDU.scala:6:7, :48:59]
        R_14 = _RANDOM[4'hD];	// @[src/main/IDU.scala:6:7, :48:59]
        R_15 = _RANDOM[4'hE];	// @[src/main/IDU.scala:6:7, :48:59]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/IDU.scala:6:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/IDU.scala:6:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid = io_in_valid;	// @[src/main/IDU.scala:6:7]
  assign io_out_bits_src1 =
    isUtype | isJtype
      ? 32'h0
      : R_1 & {32{io_in_bits_inst[19:15] == 5'h1}} | R_2
        & {32{io_in_bits_inst[19:15] == 5'h2}} | R_3
        & {32{io_in_bits_inst[19:15] == 5'h3}} | R_4
        & {32{io_in_bits_inst[19:15] == 5'h4}} | R_5
        & {32{io_in_bits_inst[19:15] == 5'h5}} | R_6
        & {32{io_in_bits_inst[19:15] == 5'h6}} | R_7
        & {32{io_in_bits_inst[19:15] == 5'h7}} | R_8
        & {32{io_in_bits_inst[19:15] == 5'h8}} | R_9
        & {32{io_in_bits_inst[19:15] == 5'h9}} | R_10
        & {32{io_in_bits_inst[19:15] == 5'hA}} | R_11
        & {32{io_in_bits_inst[19:15] == 5'hB}} | R_12
        & {32{io_in_bits_inst[19:15] == 5'hC}} | R_13
        & {32{io_in_bits_inst[19:15] == 5'hD}} | R_14
        & {32{io_in_bits_inst[19:15] == 5'hE}} | R_15
        & {32{io_in_bits_inst[19:15] == 5'hF}};	// @[src/main/IDU.scala:6:7, :18:28, :19:28, :48:59, :49:{66,72,84,107}, :59:37, :63:30, :66:18]
  assign io_out_bits_src2 =
    (src2UseReg ? rs2Val : 32'h0)
    | (isStype
         ? {{20{io_in_bits_inst[31]}}, io_in_bits_inst[31:25], io_in_bits_inst[11:7]}
         : 32'h0)
    | (isJtype
         ? {{12{io_in_bits_inst[31]}},
            io_in_bits_inst[19:12],
            io_in_bits_inst[20],
            io_in_bits_inst[30:21],
            1'h0}
         : 32'h0) | (isUtype ? {io_in_bits_inst[31:12], 12'h0} : 32'h0)
    | (src2UseReg | isStype | isJtype | isUtype
         ? 32'h0
         : {{20{io_in_bits_inst[31]}}, io_in_bits_inst[31:20]});	// @[src/main/IDU.scala:6:7, :18:28, :19:28, :20:28, :23:45, :39:26, :40:{30,40,54,64}, :41:{25,30}, :43:{30,44}, :49:107, :64:28, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:8:{33,38}, :13:47]
  assign io_out_bits_src3 = rs2Val;	// @[src/main/IDU.scala:6:7, :49:107]
  assign io_out_bits_wen = ~(isStype | isBtype) & (|io_out_bits_rd_0);	// @[src/main/IDU.scala:6:7, :20:28, :21:28, :43:44, :74:{14,24,36,47}, :75:11]
  assign io_out_bits_rd = io_out_bits_rd_0;	// @[src/main/IDU.scala:6:7, :43:44, :75:11]
  assign io_out_bits_decode_funct3 = io_in_bits_inst[14:12];	// @[src/main/IDU.scala:6:7, :25:20]
  assign io_out_bits_decode_isLoad = io_in_bits_inst[6:2] == 5'h0;	// @[src/main/IDU.scala:6:7, :19:21, :28:27]
  assign io_out_bits_decode_isStore = isStype;	// @[src/main/IDU.scala:6:7, :20:28]
  assign io_out_bits_decode_isJmp = io_in_bits_inst[6:2] == 5'h19;	// @[src/main/IDU.scala:6:7, :19:21, :29:27]
  assign io_out_bits_snpc = io_in_bits_snpc;	// @[src/main/IDU.scala:6:7]
endmodule

module EXU(	// @[src/main/EXU.scala:6:7]
  input         io_in_valid,	// @[src/main/EXU.scala:7:14]
  input  [31:0] io_in_bits_src1,	// @[src/main/EXU.scala:7:14]
                io_in_bits_src2,	// @[src/main/EXU.scala:7:14]
                io_in_bits_src3,	// @[src/main/EXU.scala:7:14]
  input         io_in_bits_wen,	// @[src/main/EXU.scala:7:14]
  input  [3:0]  io_in_bits_rd,	// @[src/main/EXU.scala:7:14]
  input  [2:0]  io_in_bits_decode_funct3,	// @[src/main/EXU.scala:7:14]
  input         io_in_bits_decode_isLoad,	// @[src/main/EXU.scala:7:14]
                io_in_bits_decode_isStore,	// @[src/main/EXU.scala:7:14]
                io_in_bits_decode_isJmp,	// @[src/main/EXU.scala:7:14]
  input  [31:0] io_in_bits_snpc,	// @[src/main/EXU.scala:7:14]
  output        io_out_valid,	// @[src/main/EXU.scala:7:14]
  output [31:0] io_out_bits_res,	// @[src/main/EXU.scala:7:14]
  output        io_out_bits_wen,	// @[src/main/EXU.scala:7:14]
  output [3:0]  io_out_bits_rd,	// @[src/main/EXU.scala:7:14]
  output [31:0] io_out_bits_wdata,	// @[src/main/EXU.scala:7:14]
  output [3:0]  io_out_bits_wmask,	// @[src/main/EXU.scala:7:14]
  output [2:0]  io_out_bits_decode_funct3,	// @[src/main/EXU.scala:7:14]
  output        io_out_bits_decode_isLoad,	// @[src/main/EXU.scala:7:14]
                io_out_bits_decode_isStore,	// @[src/main/EXU.scala:7:14]
                io_out_bits_decode_isJmp,	// @[src/main/EXU.scala:7:14]
  output [31:0] io_out_bits_snpc,	// @[src/main/EXU.scala:7:14]
  output        io_redirect_valid,	// @[src/main/EXU.scala:7:14]
  output [31:0] io_redirect_dnpc	// @[src/main/EXU.scala:7:14]
);

  wire [31:0] _sum_T = io_in_bits_src1 + io_in_bits_src2;	// @[src/main/EXU.scala:16:21]
  reg  [7:0]  casez_tmp;	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
  always_comb begin
    casez ({1'h0, _sum_T[1:0]})	// @[src/main/EXU.scala:16:21, :20:{114,124}]
      3'b000:
        casez_tmp = 8'h1;
      3'b001:
        casez_tmp = 8'h2;
      3'b010:
        casez_tmp = 8'h4;
      3'b011:
        casez_tmp = 8'h8;
      3'b100:
        casez_tmp = 8'h10;
      3'b101:
        casez_tmp = 8'h20;
      3'b110:
        casez_tmp = 8'h40;
      default:
        casez_tmp = 8'h80;
    endcase	// @[src/main/EXU.scala:16:21, :20:{114,124}]
  end // always_comb
  assign io_out_valid = io_in_valid;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_res = _sum_T;	// @[src/main/EXU.scala:6:7, :16:21]
  assign io_out_bits_wen = io_in_bits_wen;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_rd = io_in_bits_rd;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_wdata =
    (io_in_bits_decode_funct3[1:0] == 2'h0 ? {2{{2{io_in_bits_src3[7:0]}}}} : 32'h0)
    | (io_in_bits_decode_funct3[1:0] == 2'h2 ? io_in_bits_src3 : 32'h0);	// @[src/main/EXU.scala:6:7, :19:41, :24:{26,37}, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
  assign io_out_bits_wmask =
    (io_in_bits_decode_funct3[1:0] == 2'h0 ? casez_tmp[3:0] : 4'h0)
    | {4{io_in_bits_decode_funct3[1:0] == 2'h2}};	// @[src/main/EXU.scala:6:7, :19:41, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
  assign io_out_bits_decode_funct3 = io_in_bits_decode_funct3;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_decode_isLoad = io_in_bits_decode_isLoad;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_decode_isStore = io_in_bits_decode_isStore;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_decode_isJmp = io_in_bits_decode_isJmp;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_snpc = io_in_bits_snpc;	// @[src/main/EXU.scala:6:7]
  assign io_redirect_valid = io_in_bits_decode_isJmp;	// @[src/main/EXU.scala:6:7]
  assign io_redirect_dnpc = {_sum_T[31:2], 2'h0};	// @[src/main/EXU.scala:6:7, :16:21, src/main/IFU.scala:7:{25,40}]
endmodule

module LSU(	// @[src/main/LSU.scala:6:7]
  input         clock,	// @[src/main/LSU.scala:6:7]
                reset,	// @[src/main/LSU.scala:6:7]
  output        io_mem_reqValid,	// @[src/main/LSU.scala:7:14]
  output [31:0] io_mem_addr,	// @[src/main/LSU.scala:7:14]
  output [1:0]  io_mem_size,	// @[src/main/LSU.scala:7:14]
  input         io_mem_respValid,	// @[src/main/LSU.scala:7:14]
  input  [31:0] io_mem_rdata,	// @[src/main/LSU.scala:7:14]
  output        io_mem_wen,	// @[src/main/LSU.scala:7:14]
  output [31:0] io_mem_wdata,	// @[src/main/LSU.scala:7:14]
  output [3:0]  io_mem_wmask,	// @[src/main/LSU.scala:7:14]
  input         io_in_valid,	// @[src/main/LSU.scala:7:14]
  input  [31:0] io_in_bits_res,	// @[src/main/LSU.scala:7:14]
  input         io_in_bits_wen,	// @[src/main/LSU.scala:7:14]
  input  [3:0]  io_in_bits_rd,	// @[src/main/LSU.scala:7:14]
  input  [31:0] io_in_bits_wdata,	// @[src/main/LSU.scala:7:14]
  input  [3:0]  io_in_bits_wmask,	// @[src/main/LSU.scala:7:14]
  input  [2:0]  io_in_bits_decode_funct3,	// @[src/main/LSU.scala:7:14]
  input         io_in_bits_decode_isLoad,	// @[src/main/LSU.scala:7:14]
                io_in_bits_decode_isStore,	// @[src/main/LSU.scala:7:14]
                io_in_bits_decode_isJmp,	// @[src/main/LSU.scala:7:14]
  input  [31:0] io_in_bits_snpc,	// @[src/main/LSU.scala:7:14]
  output        io_out_valid,	// @[src/main/LSU.scala:7:14]
  output [31:0] io_out_bits_res,	// @[src/main/LSU.scala:7:14]
  output        io_out_bits_wen,	// @[src/main/LSU.scala:7:14]
  output [3:0]  io_out_bits_rd	// @[src/main/LSU.scala:7:14]
);

  wire       isValidLoadStore =
    (io_in_bits_decode_isLoad | io_in_bits_decode_isStore) & io_in_valid;	// @[src/main/LSU.scala:18:{45,67}]
  reg        state;	// @[src/main/LSU.scala:24:22]
  wire       loadByte = io_in_bits_decode_funct3[1:0] == 2'h0;	// @[src/main/LSU.scala:32:24, :57:33]
  reg  [7:0] casez_tmp;	// @[src/main/LSU.scala:61:76]
  always_comb begin	// @[src/main/LSU.scala:61:76]
    casez (io_in_bits_res[1:0])	// @[src/main/LSU.scala:53:35, :61:76]
      2'b00:
        casez_tmp = io_mem_rdata[7:0];	// @[src/main/LSU.scala:40:44, :61:76]
      2'b01:
        casez_tmp = io_mem_rdata[15:8];	// @[src/main/LSU.scala:40:44, :61:76]
      2'b10:
        casez_tmp = io_mem_rdata[23:16];	// @[src/main/LSU.scala:40:44, :61:76]
      default:
        casez_tmp = io_mem_rdata[31:24];	// @[src/main/LSU.scala:40:44, :61:76]
    endcase	// @[src/main/LSU.scala:53:35, :61:76]
  end // always_comb
  always @(posedge clock) begin	// @[src/main/LSU.scala:6:7]
    if (reset)	// @[src/main/LSU.scala:6:7]
      state <= 1'h0;	// @[src/main/LSU.scala:6:7, :24:22]
    else	// @[src/main/LSU.scala:6:7]
      state <= ~state & isValidLoadStore | state & ~io_mem_respValid;	// @[src/main/LSU.scala:18:67, :24:22, :27:33, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/LSU.scala:6:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/LSU.scala:6:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/LSU.scala:6:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/LSU.scala:6:7]
    initial begin	// @[src/main/LSU.scala:6:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/LSU.scala:6:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/LSU.scala:6:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/LSU.scala:6:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/LSU.scala:6:7]
        state = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/LSU.scala:6:7, :24:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/LSU.scala:6:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/LSU.scala:6:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_mem_reqValid = isValidLoadStore & ~state;	// @[src/main/LSU.scala:6:7, :18:67, :24:22, :30:39, src/main/utils/Utils.scala:21:92]
  assign io_mem_addr = io_in_bits_res;	// @[src/main/LSU.scala:6:7]
  assign io_mem_size = io_in_bits_decode_funct3[1:0];	// @[src/main/LSU.scala:6:7, :32:24]
  assign io_mem_wen = io_in_bits_decode_isStore;	// @[src/main/LSU.scala:6:7]
  assign io_mem_wdata = io_in_bits_wdata;	// @[src/main/LSU.scala:6:7]
  assign io_mem_wmask = io_in_bits_wmask;	// @[src/main/LSU.scala:6:7]
  assign io_out_valid = io_in_valid & ~isValidLoadStore | state & io_mem_respValid;	// @[src/main/LSU.scala:6:7, :18:67, :24:22, :86:{32,35,54}, :87:51]
  assign io_out_bits_res =
    (io_in_bits_decode_isLoad
       ? {loadByte
            ? (io_in_bits_decode_funct3[2] ? 16'h0 : {16{casez_tmp[7]}})
            : io_mem_rdata[31:16],
          loadByte
            ? (io_in_bits_decode_funct3[2] ? 8'h0 : {8{casez_tmp[7]}})
            : io_in_bits_res[1] ? io_mem_rdata[31:24] : io_mem_rdata[15:8],
          casez_tmp}
       : 32'h0) | (io_in_bits_decode_isJmp ? {io_in_bits_snpc[31:2], 2'h0} : 32'h0)
    | (io_in_bits_decode_isLoad | io_in_bits_decode_isJmp ? 32'h0 : io_in_bits_res);	// @[src/main/IFU.scala:7:{25,40}, src/main/LSU.scala:6:7, :40:44, :42:42, :52:35, :56:26, :57:33, :60:{59,86}, :61:76, :66:23, :67:23, :72:23, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_out_bits_wen = io_in_bits_wen;	// @[src/main/LSU.scala:6:7]
  assign io_out_bits_rd = io_in_bits_rd;	// @[src/main/LSU.scala:6:7]
endmodule

module WBU(	// @[src/main/WBU.scala:5:7]
  input         io_in_valid,	// @[src/main/WBU.scala:6:14]
  input  [31:0] io_in_bits_res,	// @[src/main/WBU.scala:6:14]
  input         io_in_bits_wen,	// @[src/main/WBU.scala:6:14]
  input  [3:0]  io_in_bits_rd,	// @[src/main/WBU.scala:6:14]
  output [31:0] io_wb_res,	// @[src/main/WBU.scala:6:14]
  output        io_wb_wen,	// @[src/main/WBU.scala:6:14]
  output [3:0]  io_wb_rd	// @[src/main/WBU.scala:6:14]
);

  assign io_wb_res = io_in_bits_res;	// @[src/main/WBU.scala:5:7]
  assign io_wb_wen = io_in_bits_wen & io_in_valid;	// @[src/main/WBU.scala:5:7, :11:31]
  assign io_wb_rd = io_in_bits_rd;	// @[src/main/WBU.scala:5:7]
endmodule

module NPC(	// @[src/main/NPC.scala:24:7]
  input         clock,	// @[src/main/NPC.scala:24:7]
  input         reset,	// @[src/main/NPC.scala:24:7]
  output [31:0] io_ifu_addr,	// @[src/main/NPC.scala:25:14]
  output        io_ifu_reqValid,	// @[src/main/NPC.scala:25:14]
  input  [31:0] io_ifu_rdata,	// @[src/main/NPC.scala:25:14]
  input         io_ifu_respValid,	// @[src/main/NPC.scala:25:14]
  output        io_lsu_reqValid,	// @[src/main/NPC.scala:25:14]
  output [31:0] io_lsu_addr,	// @[src/main/NPC.scala:25:14]
  output [1:0]  io_lsu_size,	// @[src/main/NPC.scala:25:14]
  input         io_lsu_respValid,	// @[src/main/NPC.scala:25:14]
  input  [31:0] io_lsu_rdata,	// @[src/main/NPC.scala:25:14]
  output        io_lsu_wen,	// @[src/main/NPC.scala:25:14]
  output [31:0] io_lsu_wdata,	// @[src/main/NPC.scala:25:14]
  output [3:0]  io_lsu_wmask	// @[src/main/NPC.scala:25:14]
);

  wire [31:0] _wbu_io_wb_res;	// @[src/main/NPC.scala:38:19]
  wire        _wbu_io_wb_wen;	// @[src/main/NPC.scala:38:19]
  wire [3:0]  _wbu_io_wb_rd;	// @[src/main/NPC.scala:38:19]
  wire        _lsu_io_out_valid;	// @[src/main/NPC.scala:37:19]
  wire [31:0] _lsu_io_out_bits_res;	// @[src/main/NPC.scala:37:19]
  wire        _lsu_io_out_bits_wen;	// @[src/main/NPC.scala:37:19]
  wire [3:0]  _lsu_io_out_bits_rd;	// @[src/main/NPC.scala:37:19]
  wire        _exu_io_out_valid;	// @[src/main/NPC.scala:36:19]
  wire [31:0] _exu_io_out_bits_res;	// @[src/main/NPC.scala:36:19]
  wire        _exu_io_out_bits_wen;	// @[src/main/NPC.scala:36:19]
  wire [3:0]  _exu_io_out_bits_rd;	// @[src/main/NPC.scala:36:19]
  wire [31:0] _exu_io_out_bits_wdata;	// @[src/main/NPC.scala:36:19]
  wire [3:0]  _exu_io_out_bits_wmask;	// @[src/main/NPC.scala:36:19]
  wire [2:0]  _exu_io_out_bits_decode_funct3;	// @[src/main/NPC.scala:36:19]
  wire        _exu_io_out_bits_decode_isLoad;	// @[src/main/NPC.scala:36:19]
  wire        _exu_io_out_bits_decode_isStore;	// @[src/main/NPC.scala:36:19]
  wire        _exu_io_out_bits_decode_isJmp;	// @[src/main/NPC.scala:36:19]
  wire [31:0] _exu_io_out_bits_snpc;	// @[src/main/NPC.scala:36:19]
  wire        _exu_io_redirect_valid;	// @[src/main/NPC.scala:36:19]
  wire [31:0] _exu_io_redirect_dnpc;	// @[src/main/NPC.scala:36:19]
  wire        _idu_io_out_valid;	// @[src/main/NPC.scala:35:19]
  wire [31:0] _idu_io_out_bits_src1;	// @[src/main/NPC.scala:35:19]
  wire [31:0] _idu_io_out_bits_src2;	// @[src/main/NPC.scala:35:19]
  wire [31:0] _idu_io_out_bits_src3;	// @[src/main/NPC.scala:35:19]
  wire        _idu_io_out_bits_wen;	// @[src/main/NPC.scala:35:19]
  wire [3:0]  _idu_io_out_bits_rd;	// @[src/main/NPC.scala:35:19]
  wire [2:0]  _idu_io_out_bits_decode_funct3;	// @[src/main/NPC.scala:35:19]
  wire        _idu_io_out_bits_decode_isLoad;	// @[src/main/NPC.scala:35:19]
  wire        _idu_io_out_bits_decode_isStore;	// @[src/main/NPC.scala:35:19]
  wire        _idu_io_out_bits_decode_isJmp;	// @[src/main/NPC.scala:35:19]
  wire [31:0] _idu_io_out_bits_snpc;	// @[src/main/NPC.scala:35:19]
  wire        _ifu_io_out_valid;	// @[src/main/NPC.scala:34:19]
  wire [31:0] _ifu_io_out_bits_inst;	// @[src/main/NPC.scala:34:19]
  wire [31:0] _ifu_io_out_bits_snpc;	// @[src/main/NPC.scala:34:19]
  IFU ifu (	// @[src/main/NPC.scala:34:19]
    .clock             (clock),
    .reset             (reset),
    .io_mem_addr       (io_ifu_addr),
    .io_mem_reqValid   (io_ifu_reqValid),
    .io_mem_rdata      (io_ifu_rdata),
    .io_mem_respValid  (io_ifu_respValid),
    .io_out_valid      (_ifu_io_out_valid),
    .io_out_bits_inst  (_ifu_io_out_bits_inst),
    .io_out_bits_snpc  (_ifu_io_out_bits_snpc),
    .io_redirect_valid (_exu_io_redirect_valid),	// @[src/main/NPC.scala:36:19]
    .io_redirect_dnpc  (_exu_io_redirect_dnpc),	// @[src/main/NPC.scala:36:19]
    .io_nextInst       (_lsu_io_out_valid)	// @[src/main/NPC.scala:37:19]
  );	// @[src/main/NPC.scala:34:19]
  IDU idu (	// @[src/main/NPC.scala:35:19]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_valid                (_ifu_io_out_valid),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_inst            (_ifu_io_out_bits_inst),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_snpc            (_ifu_io_out_bits_snpc),	// @[src/main/NPC.scala:34:19]
    .io_out_valid               (_idu_io_out_valid),
    .io_out_bits_src1           (_idu_io_out_bits_src1),
    .io_out_bits_src2           (_idu_io_out_bits_src2),
    .io_out_bits_src3           (_idu_io_out_bits_src3),
    .io_out_bits_wen            (_idu_io_out_bits_wen),
    .io_out_bits_rd             (_idu_io_out_bits_rd),
    .io_out_bits_decode_funct3  (_idu_io_out_bits_decode_funct3),
    .io_out_bits_decode_isLoad  (_idu_io_out_bits_decode_isLoad),
    .io_out_bits_decode_isStore (_idu_io_out_bits_decode_isStore),
    .io_out_bits_decode_isJmp   (_idu_io_out_bits_decode_isJmp),
    .io_out_bits_snpc           (_idu_io_out_bits_snpc),
    .io_wb_res                  (_wbu_io_wb_res),	// @[src/main/NPC.scala:38:19]
    .io_wb_wen                  (_wbu_io_wb_wen),	// @[src/main/NPC.scala:38:19]
    .io_wb_rd                   (_wbu_io_wb_rd)	// @[src/main/NPC.scala:38:19]
  );	// @[src/main/NPC.scala:35:19]
  EXU exu (	// @[src/main/NPC.scala:36:19]
    .io_in_valid                (_idu_io_out_valid),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_src1            (_idu_io_out_bits_src1),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_src2            (_idu_io_out_bits_src2),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_src3            (_idu_io_out_bits_src3),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_wen             (_idu_io_out_bits_wen),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_rd              (_idu_io_out_bits_rd),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_decode_funct3   (_idu_io_out_bits_decode_funct3),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_decode_isLoad   (_idu_io_out_bits_decode_isLoad),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_decode_isStore  (_idu_io_out_bits_decode_isStore),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_decode_isJmp    (_idu_io_out_bits_decode_isJmp),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_snpc            (_idu_io_out_bits_snpc),	// @[src/main/NPC.scala:35:19]
    .io_out_valid               (_exu_io_out_valid),
    .io_out_bits_res            (_exu_io_out_bits_res),
    .io_out_bits_wen            (_exu_io_out_bits_wen),
    .io_out_bits_rd             (_exu_io_out_bits_rd),
    .io_out_bits_wdata          (_exu_io_out_bits_wdata),
    .io_out_bits_wmask          (_exu_io_out_bits_wmask),
    .io_out_bits_decode_funct3  (_exu_io_out_bits_decode_funct3),
    .io_out_bits_decode_isLoad  (_exu_io_out_bits_decode_isLoad),
    .io_out_bits_decode_isStore (_exu_io_out_bits_decode_isStore),
    .io_out_bits_decode_isJmp   (_exu_io_out_bits_decode_isJmp),
    .io_out_bits_snpc           (_exu_io_out_bits_snpc),
    .io_redirect_valid          (_exu_io_redirect_valid),
    .io_redirect_dnpc           (_exu_io_redirect_dnpc)
  );	// @[src/main/NPC.scala:36:19]
  LSU lsu (	// @[src/main/NPC.scala:37:19]
    .clock                     (clock),
    .reset                     (reset),
    .io_mem_reqValid           (io_lsu_reqValid),
    .io_mem_addr               (io_lsu_addr),
    .io_mem_size               (io_lsu_size),
    .io_mem_respValid          (io_lsu_respValid),
    .io_mem_rdata              (io_lsu_rdata),
    .io_mem_wen                (io_lsu_wen),
    .io_mem_wdata              (io_lsu_wdata),
    .io_mem_wmask              (io_lsu_wmask),
    .io_in_valid               (_exu_io_out_valid),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_res            (_exu_io_out_bits_res),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_wen            (_exu_io_out_bits_wen),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_rd             (_exu_io_out_bits_rd),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_wdata          (_exu_io_out_bits_wdata),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_wmask          (_exu_io_out_bits_wmask),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_decode_funct3  (_exu_io_out_bits_decode_funct3),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_decode_isLoad  (_exu_io_out_bits_decode_isLoad),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_decode_isStore (_exu_io_out_bits_decode_isStore),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_decode_isJmp   (_exu_io_out_bits_decode_isJmp),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_snpc           (_exu_io_out_bits_snpc),	// @[src/main/NPC.scala:36:19]
    .io_out_valid              (_lsu_io_out_valid),
    .io_out_bits_res           (_lsu_io_out_bits_res),
    .io_out_bits_wen           (_lsu_io_out_bits_wen),
    .io_out_bits_rd            (_lsu_io_out_bits_rd)
  );	// @[src/main/NPC.scala:37:19]
  WBU wbu (	// @[src/main/NPC.scala:38:19]
    .io_in_valid    (_lsu_io_out_valid),	// @[src/main/NPC.scala:37:19]
    .io_in_bits_res (_lsu_io_out_bits_res),	// @[src/main/NPC.scala:37:19]
    .io_in_bits_wen (_lsu_io_out_bits_wen),	// @[src/main/NPC.scala:37:19]
    .io_in_bits_rd  (_lsu_io_out_bits_rd),	// @[src/main/NPC.scala:37:19]
    .io_wb_res      (_wbu_io_wb_res),
    .io_wb_wen      (_wbu_io_wb_wen),
    .io_wb_rd       (_wbu_io_wb_rd)
  );	// @[src/main/NPC.scala:38:19]
endmodule

