// Generated by CIRCT firtool-1.66.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

module IFU(	// @[src/main/IFU.scala:10:7]
  input         clock,	// @[src/main/IFU.scala:10:7]
                reset,	// @[src/main/IFU.scala:10:7]
  output [31:0] io_mem_pc,	// @[src/main/IFU.scala:11:14]
  output        io_mem_pcValid,	// @[src/main/IFU.scala:11:14]
  input  [31:0] io_mem_inst,	// @[src/main/IFU.scala:11:14]
  input         io_mem_instValid,	// @[src/main/IFU.scala:11:14]
  output        io_out_valid,	// @[src/main/IFU.scala:11:14]
  output [31:0] io_out_bits_inst,	// @[src/main/IFU.scala:11:14]
                io_out_bits_snpc,	// @[src/main/IFU.scala:11:14]
  input         io_redirect_valid,	// @[src/main/IFU.scala:11:14]
  input  [31:0] io_redirect_dnpc,	// @[src/main/IFU.scala:11:14]
  input         io_nextInst	// @[src/main/IFU.scala:11:14]
);

  reg  [31:0] PC;	// @[src/main/IFU.scala:17:19]
  wire [31:0] _snpc_T = PC + 32'h4;	// @[src/main/IFU.scala:17:19, :18:17]
  reg         fetchInst_REG;	// @[src/main/IFU.scala:22:49]
  reg         fetchInst;	// @[src/main/IFU.scala:22:26]
  reg         state;	// @[src/main/IFU.scala:28:22]
  reg  [31:0] io_out_bits_inst_r;	// @[src/main/IFU.scala:37:67]
  always @(posedge clock) begin	// @[src/main/IFU.scala:10:7]
    if (reset) begin	// @[src/main/IFU.scala:10:7]
      PC <= 32'h30000000;	// @[src/main/IFU.scala:17:19]
      fetchInst_REG <= 1'h1;	// @[src/main/IFU.scala:22:49]
      fetchInst <= 1'h0;	// @[src/main/IFU.scala:22:26]
      state <= 1'h0;	// @[src/main/IFU.scala:28:22]
    end
    else begin	// @[src/main/IFU.scala:10:7]
      if (io_nextInst)	// @[src/main/IFU.scala:11:14]
        PC <= {io_redirect_valid ? io_redirect_dnpc[31:2] : _snpc_T[31:2], 2'h0};	// @[src/main/IFU.scala:7:40, :10:7, :11:14, :17:19, :18:17, :20:19]
      fetchInst_REG <= 1'h0;	// @[src/main/IFU.scala:22:49]
      fetchInst <= io_nextInst | fetchInst_REG;	// @[src/main/IFU.scala:22:{26,39,49}]
      state <= ~state & fetchInst | state & ~io_mem_instValid;	// @[src/main/IFU.scala:22:26, :28:22, :31:33, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
    end
    if (io_mem_instValid)	// @[src/main/IFU.scala:11:14]
      io_out_bits_inst_r <= io_mem_inst;	// @[src/main/IFU.scala:37:67]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/IFU.scala:10:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/IFU.scala:10:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/IFU.scala:10:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[src/main/IFU.scala:10:7]
    initial begin	// @[src/main/IFU.scala:10:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/IFU.scala:10:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/IFU.scala:10:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/IFU.scala:10:7]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[src/main/IFU.scala:10:7]
        end	// @[src/main/IFU.scala:10:7]
        PC = _RANDOM[2'h0];	// @[src/main/IFU.scala:10:7, :17:19]
        fetchInst_REG = _RANDOM[2'h1][0];	// @[src/main/IFU.scala:10:7, :22:49]
        fetchInst = _RANDOM[2'h1][1];	// @[src/main/IFU.scala:10:7, :22:{26,49}]
        state = _RANDOM[2'h1][2];	// @[src/main/IFU.scala:10:7, :22:49, :28:22]
        io_out_bits_inst_r = {_RANDOM[2'h1][31:3], _RANDOM[2'h2][2:0]};	// @[src/main/IFU.scala:10:7, :22:49, :37:67]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/IFU.scala:10:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/IFU.scala:10:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_mem_pc = {PC[31:2], 2'h0};	// @[src/main/IFU.scala:7:{25,40}, :10:7, :17:19]
  assign io_mem_pcValid = fetchInst & ~state;	// @[src/main/IFU.scala:10:7, :22:26, :28:22, :34:31, src/main/utils/Utils.scala:21:92]
  assign io_out_valid = io_mem_instValid;	// @[src/main/IFU.scala:10:7]
  assign io_out_bits_inst = io_mem_instValid ? io_mem_inst : io_out_bits_inst_r;	// @[src/main/IFU.scala:10:7, :37:{26,67}]
  assign io_out_bits_snpc = _snpc_T;	// @[src/main/IFU.scala:10:7, :18:17]
endmodule

// VCS coverage exclude_file
module R_16x32(	// @[src/main/IDU.scala:47:14]
  input  [3:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [3:0]  R1_addr,
  input         R1_en,
                R1_clk,
  output [31:0] R1_data,
  input  [3:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:15];	// @[src/main/IDU.scala:47:14]
  always @(posedge W0_clk) begin	// @[src/main/IDU.scala:47:14]
    if (W0_en & 1'h1)	// @[src/main/IDU.scala:47:14]
      Memory[W0_addr] <= W0_data;	// @[src/main/IDU.scala:47:14]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// @[src/main/IDU.scala:47:14]
    reg [31:0] _RANDOM_MEM;	// @[src/main/IDU.scala:47:14]
    initial begin	// @[src/main/IDU.scala:47:14]
      `INIT_RANDOM_PROLOG_	// @[src/main/IDU.scala:47:14]
      `ifdef RANDOMIZE_MEM_INIT	// @[src/main/IDU.scala:47:14]
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          _RANDOM_MEM = `RANDOM;	// @[src/main/IDU.scala:47:14]
          Memory[i[3:0]] = _RANDOM_MEM;	// @[src/main/IDU.scala:47:14]
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// @[src/main/IDU.scala:47:14]
  assign R1_data = R1_en ? Memory[R1_addr] : 32'bx;	// @[src/main/IDU.scala:47:14]
endmodule

module IDU(	// @[src/main/IDU.scala:6:7]
  input         clock,	// @[src/main/IDU.scala:6:7]
                reset,	// @[src/main/IDU.scala:6:7]
                io_in_valid,	// @[src/main/IDU.scala:7:14]
  input  [31:0] io_in_bits_inst,	// @[src/main/IDU.scala:7:14]
                io_in_bits_snpc,	// @[src/main/IDU.scala:7:14]
  output        io_out_valid,	// @[src/main/IDU.scala:7:14]
  output [31:0] io_out_bits_src1,	// @[src/main/IDU.scala:7:14]
                io_out_bits_src2,	// @[src/main/IDU.scala:7:14]
                io_out_bits_src3,	// @[src/main/IDU.scala:7:14]
  output        io_out_bits_wen,	// @[src/main/IDU.scala:7:14]
  output [3:0]  io_out_bits_rd,	// @[src/main/IDU.scala:7:14]
  output [2:0]  io_out_bits_decode_funct3,	// @[src/main/IDU.scala:7:14]
  output        io_out_bits_decode_isLoad,	// @[src/main/IDU.scala:7:14]
                io_out_bits_decode_isStore,	// @[src/main/IDU.scala:7:14]
                io_out_bits_decode_isJmp,	// @[src/main/IDU.scala:7:14]
  output [31:0] io_out_bits_snpc,	// @[src/main/IDU.scala:7:14]
  input  [31:0] io_wb_res,	// @[src/main/IDU.scala:7:14]
  input         io_wb_wen,	// @[src/main/IDU.scala:7:14]
  input  [3:0]  io_wb_rd	// @[src/main/IDU.scala:7:14]
);

  wire [3:0]  io_out_bits_rd_0;	// @[src/main/IDU.scala:43:44, :65:11]
  wire [31:0] _R_ext_R0_data;	// @[src/main/IDU.scala:47:14]
  wire [31:0] _R_ext_R1_data;	// @[src/main/IDU.scala:47:14]
  wire        isUtype = io_in_bits_inst[4:2] == 3'h5;	// @[src/main/IDU.scala:18:{21,28}]
  wire        isJtype = io_in_bits_inst[6:2] == 5'h1B;	// @[src/main/IDU.scala:19:{21,28}]
  wire        isStype = io_in_bits_inst[6:2] == 5'h8;	// @[src/main/IDU.scala:19:21, :20:28]
  wire        isBtype = io_in_bits_inst[6:2] == 5'h18;	// @[src/main/IDU.scala:19:21, :21:28]
  `ifndef SYNTHESIS	// @[src/main/IDU.scala:45:9]
    wire [9:0] _GEN = {io_in_bits_inst[14:12], io_in_bits_inst[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
    always @(posedge clock) begin	// @[src/main/IDU.scala:45:9]
      if (~reset
          & ~(~io_in_valid
              | ~(~(_GEN == 10'h13
                    | {io_in_bits_inst[31:25],
                       io_in_bits_inst[14:12],
                       io_in_bits_inst[6:0]} == 17'h33 | io_in_bits_inst[6:0] == 7'h37
                    | _GEN == 10'h67 | _GEN == 10'h203 | _GEN == 10'h103 | _GEN == 10'h23
                    | _GEN == 10'h123) & io_in_bits_inst != 32'h100073))) begin	// @[src/main/IDU.scala:45:{9,10,23,50}, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
        if (`ASSERT_VERBOSE_COND_)	// @[src/main/IDU.scala:45:9]
          $error("Assertion failed: Invalid instruction 0x%x\n    at IDU.scala:45 assert(!io.in.valid || AllInst.isIllegal(inst) === false.B, \"Invalid instruction 0x%%%%x\", inst)\n",
                 io_in_bits_inst);	// @[src/main/IDU.scala:45:9]
        if (`STOP_COND_)	// @[src/main/IDU.scala:45:9]
          $fatal;	// @[src/main/IDU.scala:45:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _rs2Val_T = io_in_bits_inst[24:20] == 5'h0;	// @[src/main/IDU.scala:48:34, :50:37]
  wire        src2UseReg =
    io_in_bits_inst[6:2] == 5'hC | io_in_bits_inst[6:2] == 5'hE | isBtype;	// @[src/main/IDU.scala:19:21, :21:28, :23:{29,45,60}, :54:28]
  assign io_out_bits_rd_0 = io_in_bits_inst[10:7];	// @[src/main/IDU.scala:43:44, :65:11]
  R_16x32 R_ext (	// @[src/main/IDU.scala:47:14]
    .R0_addr (io_in_bits_inst[23:20]),	// @[src/main/IDU.scala:48:49, :50:37]
    .R0_en   (1'h1),	// @[src/main/IDU.scala:6:7]
    .R0_clk  (clock),
    .R0_data (_R_ext_R0_data),
    .R1_addr (io_in_bits_inst[18:15]),	// @[src/main/IDU.scala:48:49, :49:37]
    .R1_en   (1'h1),	// @[src/main/IDU.scala:6:7]
    .R1_clk  (clock),
    .R1_data (_R_ext_R1_data),
    .W0_addr (io_wb_rd),
    .W0_en   (io_wb_wen),
    .W0_clk  (clock),
    .W0_data (io_wb_res)
  );	// @[src/main/IDU.scala:47:14]
  assign io_out_valid = io_in_valid;	// @[src/main/IDU.scala:6:7]
  assign io_out_bits_src1 =
    isUtype | isJtype | io_in_bits_inst[19:15] == 5'h0 ? 32'h0 : _R_ext_R1_data;	// @[src/main/IDU.scala:6:7, :18:28, :19:28, :47:14, :48:34, :49:37, :53:30, :56:18]
  assign io_out_bits_src2 =
    (~src2UseReg | _rs2Val_T ? 32'h0 : _R_ext_R0_data)
    | (isStype
         ? {{20{io_in_bits_inst[31]}}, io_in_bits_inst[31:25], io_in_bits_inst[11:7]}
         : 32'h0)
    | (isJtype
         ? {{12{io_in_bits_inst[31]}},
            io_in_bits_inst[19:12],
            io_in_bits_inst[20],
            io_in_bits_inst[30:21],
            1'h0}
         : 32'h0) | (isUtype ? {io_in_bits_inst[31:12], 12'h0} : 32'h0)
    | (src2UseReg | isStype | isJtype | isUtype
         ? 32'h0
         : {{20{io_in_bits_inst[31]}}, io_in_bits_inst[31:20]});	// @[src/main/IDU.scala:6:7, :18:28, :19:28, :20:28, :23:45, :39:26, :40:{30,40,54,64}, :41:{25,30}, :43:{30,44}, :47:14, :48:34, :54:28, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:8:{33,38}, :13:47]
  assign io_out_bits_src3 = _rs2Val_T ? 32'h0 : _R_ext_R0_data;	// @[src/main/IDU.scala:6:7, :47:14, :48:{29,34}]
  assign io_out_bits_wen = ~(isStype | isBtype) & (|io_out_bits_rd_0);	// @[src/main/IDU.scala:6:7, :20:28, :21:28, :43:44, :64:{14,24,36,47}, :65:11]
  assign io_out_bits_rd = io_out_bits_rd_0;	// @[src/main/IDU.scala:6:7, :43:44, :65:11]
  assign io_out_bits_decode_funct3 = io_in_bits_inst[14:12];	// @[src/main/IDU.scala:6:7, :25:20]
  assign io_out_bits_decode_isLoad = io_in_bits_inst[6:2] == 5'h0;	// @[src/main/IDU.scala:6:7, :19:21, :28:27]
  assign io_out_bits_decode_isStore = isStype;	// @[src/main/IDU.scala:6:7, :20:28]
  assign io_out_bits_decode_isJmp = io_in_bits_inst[6:2] == 5'h19;	// @[src/main/IDU.scala:6:7, :19:21, :29:27]
  assign io_out_bits_snpc = io_in_bits_snpc;	// @[src/main/IDU.scala:6:7]
endmodule

module EXU(	// @[src/main/EXU.scala:6:7]
  input         io_in_valid,	// @[src/main/EXU.scala:7:14]
  input  [31:0] io_in_bits_src1,	// @[src/main/EXU.scala:7:14]
                io_in_bits_src2,	// @[src/main/EXU.scala:7:14]
                io_in_bits_src3,	// @[src/main/EXU.scala:7:14]
  input         io_in_bits_wen,	// @[src/main/EXU.scala:7:14]
  input  [3:0]  io_in_bits_rd,	// @[src/main/EXU.scala:7:14]
  input  [2:0]  io_in_bits_decode_funct3,	// @[src/main/EXU.scala:7:14]
  input         io_in_bits_decode_isLoad,	// @[src/main/EXU.scala:7:14]
                io_in_bits_decode_isStore,	// @[src/main/EXU.scala:7:14]
                io_in_bits_decode_isJmp,	// @[src/main/EXU.scala:7:14]
  input  [31:0] io_in_bits_snpc,	// @[src/main/EXU.scala:7:14]
  output        io_out_valid,	// @[src/main/EXU.scala:7:14]
  output [31:0] io_out_bits_res,	// @[src/main/EXU.scala:7:14]
  output        io_out_bits_wen,	// @[src/main/EXU.scala:7:14]
  output [3:0]  io_out_bits_rd,	// @[src/main/EXU.scala:7:14]
  output [31:0] io_out_bits_wdata,	// @[src/main/EXU.scala:7:14]
  output [3:0]  io_out_bits_wmask,	// @[src/main/EXU.scala:7:14]
  output [2:0]  io_out_bits_decode_funct3,	// @[src/main/EXU.scala:7:14]
  output        io_out_bits_decode_isLoad,	// @[src/main/EXU.scala:7:14]
                io_out_bits_decode_isStore,	// @[src/main/EXU.scala:7:14]
                io_out_bits_decode_isJmp,	// @[src/main/EXU.scala:7:14]
  output [31:0] io_out_bits_snpc,	// @[src/main/EXU.scala:7:14]
  output        io_redirect_valid,	// @[src/main/EXU.scala:7:14]
  output [31:0] io_redirect_dnpc	// @[src/main/EXU.scala:7:14]
);

  wire [31:0] _sum_T = io_in_bits_src1 + io_in_bits_src2;	// @[src/main/EXU.scala:16:21]
  reg  [7:0]  casez_tmp;	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
  always_comb begin
    casez ({1'h0, _sum_T[1:0]})	// @[src/main/EXU.scala:16:21, :20:{114,124}]
      3'b000:
        casez_tmp = 8'h1;
      3'b001:
        casez_tmp = 8'h2;
      3'b010:
        casez_tmp = 8'h4;
      3'b011:
        casez_tmp = 8'h8;
      3'b100:
        casez_tmp = 8'h10;
      3'b101:
        casez_tmp = 8'h20;
      3'b110:
        casez_tmp = 8'h40;
      default:
        casez_tmp = 8'h80;
    endcase	// @[src/main/EXU.scala:16:21, :20:{114,124}]
  end // always_comb
  assign io_out_valid = io_in_valid;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_res = _sum_T;	// @[src/main/EXU.scala:6:7, :16:21]
  assign io_out_bits_wen = io_in_bits_wen;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_rd = io_in_bits_rd;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_wdata =
    (io_in_bits_decode_funct3[1:0] == 2'h0 ? {2{{2{io_in_bits_src3[7:0]}}}} : 32'h0)
    | (io_in_bits_decode_funct3[1:0] == 2'h2 ? io_in_bits_src3 : 32'h0);	// @[src/main/EXU.scala:6:7, :19:41, :24:{26,37}, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
  assign io_out_bits_wmask =
    (io_in_bits_decode_funct3[1:0] == 2'h0 ? casez_tmp[3:0] : 4'h0)
    | {4{io_in_bits_decode_funct3[1:0] == 2'h2}};	// @[src/main/EXU.scala:6:7, :19:41, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
  assign io_out_bits_decode_funct3 = io_in_bits_decode_funct3;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_decode_isLoad = io_in_bits_decode_isLoad;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_decode_isStore = io_in_bits_decode_isStore;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_decode_isJmp = io_in_bits_decode_isJmp;	// @[src/main/EXU.scala:6:7]
  assign io_out_bits_snpc = io_in_bits_snpc;	// @[src/main/EXU.scala:6:7]
  assign io_redirect_valid = io_in_bits_decode_isJmp;	// @[src/main/EXU.scala:6:7]
  assign io_redirect_dnpc = {_sum_T[31:2], 2'h0};	// @[src/main/EXU.scala:6:7, :16:21, src/main/IFU.scala:7:{25,40}]
endmodule

module LSU(	// @[src/main/LSU.scala:6:7]
  input         clock,	// @[src/main/LSU.scala:6:7]
                reset,	// @[src/main/LSU.scala:6:7]
  output        io_mem_reqValid,	// @[src/main/LSU.scala:7:14]
  output [31:0] io_mem_addr,	// @[src/main/LSU.scala:7:14]
  output [1:0]  io_mem_size,	// @[src/main/LSU.scala:7:14]
  input         io_mem_respValid,	// @[src/main/LSU.scala:7:14]
  input  [31:0] io_mem_rdata,	// @[src/main/LSU.scala:7:14]
  output        io_mem_wen,	// @[src/main/LSU.scala:7:14]
  output [31:0] io_mem_wdata,	// @[src/main/LSU.scala:7:14]
  output [3:0]  io_mem_wmask,	// @[src/main/LSU.scala:7:14]
  input         io_in_valid,	// @[src/main/LSU.scala:7:14]
  input  [31:0] io_in_bits_res,	// @[src/main/LSU.scala:7:14]
  input         io_in_bits_wen,	// @[src/main/LSU.scala:7:14]
  input  [3:0]  io_in_bits_rd,	// @[src/main/LSU.scala:7:14]
  input  [31:0] io_in_bits_wdata,	// @[src/main/LSU.scala:7:14]
  input  [3:0]  io_in_bits_wmask,	// @[src/main/LSU.scala:7:14]
  input  [2:0]  io_in_bits_decode_funct3,	// @[src/main/LSU.scala:7:14]
  input         io_in_bits_decode_isLoad,	// @[src/main/LSU.scala:7:14]
                io_in_bits_decode_isStore,	// @[src/main/LSU.scala:7:14]
                io_in_bits_decode_isJmp,	// @[src/main/LSU.scala:7:14]
  input  [31:0] io_in_bits_snpc,	// @[src/main/LSU.scala:7:14]
  output        io_out_valid,	// @[src/main/LSU.scala:7:14]
  output [31:0] io_out_bits_res,	// @[src/main/LSU.scala:7:14]
  output        io_out_bits_wen,	// @[src/main/LSU.scala:7:14]
  output [3:0]  io_out_bits_rd	// @[src/main/LSU.scala:7:14]
);

  wire       isValidLoadStore =
    (io_in_bits_decode_isLoad | io_in_bits_decode_isStore) & io_in_valid;	// @[src/main/LSU.scala:18:{45,67}]
  reg        state;	// @[src/main/LSU.scala:24:22]
  wire       loadByte = io_in_bits_decode_funct3[1:0] == 2'h0;	// @[src/main/LSU.scala:32:24, :57:33]
  reg  [7:0] casez_tmp;	// @[src/main/LSU.scala:61:76]
  always_comb begin	// @[src/main/LSU.scala:61:76]
    casez (io_in_bits_res[1:0])	// @[src/main/LSU.scala:53:35, :61:76]
      2'b00:
        casez_tmp = io_mem_rdata[7:0];	// @[src/main/LSU.scala:40:44, :61:76]
      2'b01:
        casez_tmp = io_mem_rdata[15:8];	// @[src/main/LSU.scala:40:44, :61:76]
      2'b10:
        casez_tmp = io_mem_rdata[23:16];	// @[src/main/LSU.scala:40:44, :61:76]
      default:
        casez_tmp = io_mem_rdata[31:24];	// @[src/main/LSU.scala:40:44, :61:76]
    endcase	// @[src/main/LSU.scala:53:35, :61:76]
  end // always_comb
  always @(posedge clock) begin	// @[src/main/LSU.scala:6:7]
    if (reset)	// @[src/main/LSU.scala:6:7]
      state <= 1'h0;	// @[src/main/LSU.scala:6:7, :24:22]
    else	// @[src/main/LSU.scala:6:7]
      state <= ~state & isValidLoadStore | state & ~io_mem_respValid;	// @[src/main/LSU.scala:18:67, :24:22, :27:33, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/LSU.scala:6:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/LSU.scala:6:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/LSU.scala:6:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[src/main/LSU.scala:6:7]
    initial begin	// @[src/main/LSU.scala:6:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/LSU.scala:6:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/LSU.scala:6:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/LSU.scala:6:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[src/main/LSU.scala:6:7]
        state = _RANDOM[/*Zero width*/ 1'b0][0];	// @[src/main/LSU.scala:6:7, :24:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/LSU.scala:6:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/LSU.scala:6:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_mem_reqValid = isValidLoadStore & ~state;	// @[src/main/LSU.scala:6:7, :18:67, :24:22, :30:39, src/main/utils/Utils.scala:21:92]
  assign io_mem_addr = io_in_bits_res;	// @[src/main/LSU.scala:6:7]
  assign io_mem_size = io_in_bits_decode_funct3[1:0];	// @[src/main/LSU.scala:6:7, :32:24]
  assign io_mem_wen = io_in_bits_decode_isStore;	// @[src/main/LSU.scala:6:7]
  assign io_mem_wdata = io_in_bits_wdata;	// @[src/main/LSU.scala:6:7]
  assign io_mem_wmask = io_in_bits_wmask;	// @[src/main/LSU.scala:6:7]
  assign io_out_valid = io_in_valid & ~isValidLoadStore | state & io_mem_respValid;	// @[src/main/LSU.scala:6:7, :18:67, :24:22, :86:{32,35,54}, :87:51]
  assign io_out_bits_res =
    (io_in_bits_decode_isLoad
       ? {loadByte
            ? (io_in_bits_decode_funct3[2] ? 16'h0 : {16{casez_tmp[7]}})
            : io_mem_rdata[31:16],
          loadByte
            ? (io_in_bits_decode_funct3[2] ? 8'h0 : {8{casez_tmp[7]}})
            : io_in_bits_res[1] ? io_mem_rdata[31:24] : io_mem_rdata[15:8],
          casez_tmp}
       : 32'h0) | (io_in_bits_decode_isJmp ? {io_in_bits_snpc[31:2], 2'h0} : 32'h0)
    | (io_in_bits_decode_isLoad | io_in_bits_decode_isJmp ? 32'h0 : io_in_bits_res);	// @[src/main/IFU.scala:7:{25,40}, src/main/LSU.scala:6:7, :40:44, :42:42, :52:35, :56:26, :57:33, :60:{59,86}, :61:76, :66:23, :67:23, :72:23, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_out_bits_wen = io_in_bits_wen;	// @[src/main/LSU.scala:6:7]
  assign io_out_bits_rd = io_in_bits_rd;	// @[src/main/LSU.scala:6:7]
endmodule

module WBU(	// @[src/main/WBU.scala:5:7]
  input         io_in_valid,	// @[src/main/WBU.scala:6:14]
  input  [31:0] io_in_bits_res,	// @[src/main/WBU.scala:6:14]
  input         io_in_bits_wen,	// @[src/main/WBU.scala:6:14]
  input  [3:0]  io_in_bits_rd,	// @[src/main/WBU.scala:6:14]
  output [31:0] io_wb_res,	// @[src/main/WBU.scala:6:14]
  output        io_wb_wen,	// @[src/main/WBU.scala:6:14]
  output [3:0]  io_wb_rd	// @[src/main/WBU.scala:6:14]
);

  assign io_wb_res = io_in_bits_res;	// @[src/main/WBU.scala:5:7]
  assign io_wb_wen = io_in_bits_wen & io_in_valid;	// @[src/main/WBU.scala:5:7, :11:31]
  assign io_wb_rd = io_in_bits_rd;	// @[src/main/WBU.scala:5:7]
endmodule

module MemBridge(	// @[src/main/Memory.scala:7:7]
  input         clock,	// @[src/main/Memory.scala:7:7]
                reset,	// @[src/main/Memory.scala:7:7]
  input  [31:0] io_ifu_pc,	// @[src/main/Memory.scala:8:14]
  input         io_ifu_pcValid,	// @[src/main/Memory.scala:8:14]
  output [31:0] io_ifu_inst,	// @[src/main/Memory.scala:8:14]
  output        io_ifu_instValid,	// @[src/main/Memory.scala:8:14]
  input         io_lsu_reqValid,	// @[src/main/Memory.scala:8:14]
  input  [31:0] io_lsu_addr,	// @[src/main/Memory.scala:8:14]
  input  [1:0]  io_lsu_size,	// @[src/main/Memory.scala:8:14]
  output        io_lsu_respValid,	// @[src/main/Memory.scala:8:14]
  output [31:0] io_lsu_rdata,	// @[src/main/Memory.scala:8:14]
  input         io_lsu_wen,	// @[src/main/Memory.scala:8:14]
  input  [31:0] io_lsu_wdata,	// @[src/main/Memory.scala:8:14]
  input  [3:0]  io_lsu_wmask,	// @[src/main/Memory.scala:8:14]
  input         io_out_awready,	// @[src/main/Memory.scala:8:14]
  output        io_out_awvalid,	// @[src/main/Memory.scala:8:14]
  output [31:0] io_out_awaddr,	// @[src/main/Memory.scala:8:14]
  output [2:0]  io_out_awsize,	// @[src/main/Memory.scala:8:14]
  input         io_out_wready,	// @[src/main/Memory.scala:8:14]
  output        io_out_wvalid,	// @[src/main/Memory.scala:8:14]
  output [31:0] io_out_wdata,	// @[src/main/Memory.scala:8:14]
  output [3:0]  io_out_wstrb,	// @[src/main/Memory.scala:8:14]
  output        io_out_bready,	// @[src/main/Memory.scala:8:14]
  input         io_out_bvalid,	// @[src/main/Memory.scala:8:14]
                io_out_arready,	// @[src/main/Memory.scala:8:14]
  output        io_out_arvalid,	// @[src/main/Memory.scala:8:14]
  output [31:0] io_out_araddr,	// @[src/main/Memory.scala:8:14]
  output [2:0]  io_out_arsize,	// @[src/main/Memory.scala:8:14]
  output        io_out_rready,	// @[src/main/Memory.scala:8:14]
  input         io_out_rvalid,	// @[src/main/Memory.scala:8:14]
  input  [31:0] io_out_rdata	// @[src/main/Memory.scala:8:14]
);

  wire        isValidLoad = io_lsu_reqValid & ~io_lsu_wen;	// @[src/main/Memory.scala:14:{38,41}]
  wire        isValidStore = io_lsu_reqValid & io_lsu_wen;	// @[src/main/Memory.scala:15:38]
  reg  [1:0]  stateI;	// @[src/main/Memory.scala:25:23]
  wire        _io_out_arvalid_T = stateI == 2'h0;	// @[src/main/Memory.scala:7:7, :25:23, src/main/utils/Utils.scala:21:92]
  wire        _io_out_arvalid_T_2 = stateI == 2'h1;	// @[src/main/Memory.scala:7:7, :25:23, src/main/utils/Utils.scala:21:92]
  wire        _instReturn_T = stateI == 2'h2;	// @[src/main/Memory.scala:7:7, :25:23, src/main/utils/Utils.scala:21:92]
  reg  [2:0]  stateD;	// @[src/main/Memory.scala:33:23]
  wire        _io_out_wvalid_T = stateD == 3'h0;	// @[src/main/Memory.scala:33:23, src/main/utils/Utils.scala:21:92]
  wire        _lsuRead_T_2 = stateD == 3'h1;	// @[src/main/Memory.scala:33:23, src/main/utils/Utils.scala:21:92]
  wire        _io_lsu_respValid_T = stateD == 3'h2;	// @[src/main/Memory.scala:33:23, src/main/utils/Utils.scala:21:92]
  wire        _io_out_awvalid_T_2 = stateD == 3'h3;	// @[src/main/Memory.scala:33:23, src/main/utils/Utils.scala:21:92]
  wire        _io_out_awvalid_T_3 = stateD == 3'h5;	// @[src/main/Memory.scala:33:23, src/main/utils/Utils.scala:21:92]
  wire        _io_out_wvalid_T_2 = stateD == 3'h4;	// @[src/main/Memory.scala:33:23, src/main/utils/Utils.scala:21:92]
  wire        io_out_bready_0 = stateD == 3'h6;	// @[src/main/Memory.scala:33:23, src/main/utils/Utils.scala:21:92]
  wire        lsuRead = _io_out_wvalid_T & isValidLoad | _lsuRead_T_2;	// @[src/main/Memory.scala:14:38, :51:{46,62}, src/main/utils/Utils.scala:21:92]
  wire        instReturn = io_out_rvalid & _instReturn_T;	// @[src/main/Memory.scala:72:35, src/main/utils/Utils.scala:21:92]
  reg  [31:0] io_ifu_inst_r;	// @[src/main/Memory.scala:73:63]
  wire [1:0]  _stateD_T_22 = io_out_arready ? 2'h2 : 2'h1;	// @[src/main/Memory.scala:7:7, :27:53]
  wire [1:0]  _stateD_T_24 = {~io_out_rvalid, 1'h0};	// @[src/main/Memory.scala:7:7, :30:33]
  wire [2:0]  _stateD_T_30 = {1'h1, io_out_wready, 1'h0};	// @[src/main/Memory.scala:7:7, :38:39]
  wire [2:0]  _stateD_T_21 =
    _io_out_wvalid_T
      ? (isValidLoad
           ? {1'h0, _stateD_T_22}
           : isValidStore
               ? (io_out_awready ? _stateD_T_30 : io_out_wready ? 3'h5 : 3'h3)
               : 3'h0)
      : 3'h0;	// @[src/main/Memory.scala:7:7, :14:38, :15:38, :27:53, :33:23, :35:33, :36:35, :37:37, :38:39, :39:39, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
  always @(posedge clock) begin	// @[src/main/Memory.scala:7:7]
    if (reset) begin	// @[src/main/Memory.scala:7:7]
      stateI <= 2'h0;	// @[src/main/Memory.scala:7:7, :25:23]
      stateD <= 3'h0;	// @[src/main/Memory.scala:33:23]
    end
    else begin	// @[src/main/Memory.scala:7:7]
      stateI <=
        (_io_out_arvalid_T & io_ifu_pcValid | _io_out_arvalid_T_2 ? _stateD_T_22 : 2'h0)
        | (_instReturn_T ? _stateD_T_24 : 2'h0);	// @[src/main/Memory.scala:7:7, :25:23, :27:{33,53}, :30:33, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
      stateD <=
        {_stateD_T_21[2],
         _stateD_T_21[1:0] | (_lsuRead_T_2 ? _stateD_T_22 : 2'h0)
           | (_io_lsu_respValid_T ? _stateD_T_24 : 2'h0)}
        | (_io_out_awvalid_T_2 ? (io_out_awready ? _stateD_T_30 : 3'h3) : 3'h0)
        | (_io_out_awvalid_T_3 ? (io_out_awready ? 3'h6 : 3'h5) : 3'h0)
        | (_io_out_wvalid_T_2 ? _stateD_T_30 : 3'h0)
        | (~io_out_bready_0 | io_out_bvalid ? 3'h0 : 3'h6);	// @[src/main/Memory.scala:7:7, :27:53, :30:33, :33:23, :38:39, :43:33, :46:33, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/utils/Utils.scala:21:92]
    end
    if (instReturn)	// @[src/main/Memory.scala:72:35]
      io_ifu_inst_r <= io_out_rdata;	// @[src/main/Memory.scala:73:63]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[src/main/Memory.scala:7:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[src/main/Memory.scala:7:7]
      `FIRRTL_BEFORE_INITIAL	// @[src/main/Memory.scala:7:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:1];	// @[src/main/Memory.scala:7:7]
    initial begin	// @[src/main/Memory.scala:7:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[src/main/Memory.scala:7:7]
        `INIT_RANDOM_PROLOG_	// @[src/main/Memory.scala:7:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[src/main/Memory.scala:7:7]
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// @[src/main/Memory.scala:7:7]
        end	// @[src/main/Memory.scala:7:7]
        stateI = _RANDOM[1'h0][1:0];	// @[src/main/Memory.scala:7:7, :25:23]
        stateD = _RANDOM[1'h0][4:2];	// @[src/main/Memory.scala:7:7, :25:23, :33:23]
        io_ifu_inst_r = {_RANDOM[1'h0][31:5], _RANDOM[1'h1][4:0]};	// @[src/main/Memory.scala:7:7, :25:23, :73:63]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[src/main/Memory.scala:7:7]
      `FIRRTL_AFTER_INITIAL	// @[src/main/Memory.scala:7:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_ifu_inst = instReturn ? io_out_rdata : io_ifu_inst_r;	// @[src/main/Memory.scala:7:7, :72:35, :73:{21,63}]
  assign io_ifu_instValid = instReturn;	// @[src/main/Memory.scala:7:7, :72:35]
  assign io_lsu_respValid =
    _io_lsu_respValid_T & io_out_rvalid | io_out_bready_0 & io_out_bvalid;	// @[src/main/Memory.scala:7:7, :77:{58,77}, :78:58, src/main/utils/Utils.scala:21:92]
  assign io_lsu_rdata = io_out_rdata;	// @[src/main/Memory.scala:7:7]
  assign io_out_awvalid =
    _io_out_wvalid_T & isValidStore | (|{_io_out_awvalid_T_3, _io_out_awvalid_T_2});	// @[src/main/Memory.scala:7:7, :15:38, :60:{51,68,85}, src/main/utils/Utils.scala:21:92]
  assign io_out_awaddr = io_lsu_addr;	// @[src/main/Memory.scala:7:7]
  assign io_out_awsize = {1'h0, io_lsu_size};	// @[src/main/Memory.scala:7:7, :62:23]
  assign io_out_wvalid = _io_out_wvalid_T & isValidStore | _io_out_wvalid_T_2;	// @[src/main/Memory.scala:7:7, :15:38, :66:{51,68}, src/main/utils/Utils.scala:21:92]
  assign io_out_wdata = io_lsu_wdata;	// @[src/main/Memory.scala:7:7]
  assign io_out_wstrb = io_lsu_wmask;	// @[src/main/Memory.scala:7:7]
  assign io_out_bready = io_out_bready_0;	// @[src/main/Memory.scala:7:7, src/main/utils/Utils.scala:21:92]
  assign io_out_arvalid =
    _io_out_arvalid_T & io_ifu_pcValid | _io_out_arvalid_T_2 | lsuRead;	// @[src/main/Memory.scala:7:7, :51:62, :52:{51,70,108}, src/main/utils/Utils.scala:21:92]
  assign io_out_araddr = lsuRead ? io_lsu_addr : io_ifu_pc;	// @[src/main/Memory.scala:7:7, :51:62, :53:29]
  assign io_out_arsize = {1'h0, lsuRead ? io_lsu_size : 2'h2};	// @[src/main/Memory.scala:7:7, :51:62, :54:{23,29}]
  assign io_out_rready = _instReturn_T | _io_lsu_respValid_T;	// @[src/main/Memory.scala:7:7, :58:56, src/main/utils/Utils.scala:21:92]
endmodule

module NPC(	// @[src/main/NPC.scala:24:7]
  input         clock,	// @[src/main/NPC.scala:24:7]
                reset,	// @[src/main/NPC.scala:24:7]
                io_master_awready,	// @[src/main/NPC.scala:25:14]
  output        io_master_awvalid,	// @[src/main/NPC.scala:25:14]
  output [31:0] io_master_awaddr,	// @[src/main/NPC.scala:25:14]
  output [2:0]  io_master_awsize,	// @[src/main/NPC.scala:25:14]
  input         io_master_wready,	// @[src/main/NPC.scala:25:14]
  output        io_master_wvalid,	// @[src/main/NPC.scala:25:14]
  output [31:0] io_master_wdata,	// @[src/main/NPC.scala:25:14]
  output [3:0]  io_master_wstrb,	// @[src/main/NPC.scala:25:14]
  output        io_master_bready,	// @[src/main/NPC.scala:25:14]
  input         io_master_bvalid,	// @[src/main/NPC.scala:25:14]
                io_master_arready,	// @[src/main/NPC.scala:25:14]
  output        io_master_arvalid,	// @[src/main/NPC.scala:25:14]
  output [31:0] io_master_araddr,	// @[src/main/NPC.scala:25:14]
  output [2:0]  io_master_arsize,	// @[src/main/NPC.scala:25:14]
  output        io_master_rready,	// @[src/main/NPC.scala:25:14]
  input         io_master_rvalid,	// @[src/main/NPC.scala:25:14]
  input  [31:0] io_master_rdata	// @[src/main/NPC.scala:25:14]
);

  wire [31:0] _bridge_io_ifu_inst;	// @[src/main/NPC.scala:54:24]
  wire        _bridge_io_ifu_instValid;	// @[src/main/NPC.scala:54:24]
  wire        _bridge_io_lsu_respValid;	// @[src/main/NPC.scala:54:24]
  wire [31:0] _bridge_io_lsu_rdata;	// @[src/main/NPC.scala:54:24]
  wire [31:0] _wbu_io_wb_res;	// @[src/main/NPC.scala:37:19]
  wire        _wbu_io_wb_wen;	// @[src/main/NPC.scala:37:19]
  wire [3:0]  _wbu_io_wb_rd;	// @[src/main/NPC.scala:37:19]
  wire        _lsu_io_mem_reqValid;	// @[src/main/NPC.scala:36:19]
  wire [31:0] _lsu_io_mem_addr;	// @[src/main/NPC.scala:36:19]
  wire [1:0]  _lsu_io_mem_size;	// @[src/main/NPC.scala:36:19]
  wire        _lsu_io_mem_wen;	// @[src/main/NPC.scala:36:19]
  wire [31:0] _lsu_io_mem_wdata;	// @[src/main/NPC.scala:36:19]
  wire [3:0]  _lsu_io_mem_wmask;	// @[src/main/NPC.scala:36:19]
  wire        _lsu_io_out_valid;	// @[src/main/NPC.scala:36:19]
  wire [31:0] _lsu_io_out_bits_res;	// @[src/main/NPC.scala:36:19]
  wire        _lsu_io_out_bits_wen;	// @[src/main/NPC.scala:36:19]
  wire [3:0]  _lsu_io_out_bits_rd;	// @[src/main/NPC.scala:36:19]
  wire        _exu_io_out_valid;	// @[src/main/NPC.scala:35:19]
  wire [31:0] _exu_io_out_bits_res;	// @[src/main/NPC.scala:35:19]
  wire        _exu_io_out_bits_wen;	// @[src/main/NPC.scala:35:19]
  wire [3:0]  _exu_io_out_bits_rd;	// @[src/main/NPC.scala:35:19]
  wire [31:0] _exu_io_out_bits_wdata;	// @[src/main/NPC.scala:35:19]
  wire [3:0]  _exu_io_out_bits_wmask;	// @[src/main/NPC.scala:35:19]
  wire [2:0]  _exu_io_out_bits_decode_funct3;	// @[src/main/NPC.scala:35:19]
  wire        _exu_io_out_bits_decode_isLoad;	// @[src/main/NPC.scala:35:19]
  wire        _exu_io_out_bits_decode_isStore;	// @[src/main/NPC.scala:35:19]
  wire        _exu_io_out_bits_decode_isJmp;	// @[src/main/NPC.scala:35:19]
  wire [31:0] _exu_io_out_bits_snpc;	// @[src/main/NPC.scala:35:19]
  wire        _exu_io_redirect_valid;	// @[src/main/NPC.scala:35:19]
  wire [31:0] _exu_io_redirect_dnpc;	// @[src/main/NPC.scala:35:19]
  wire        _idu_io_out_valid;	// @[src/main/NPC.scala:34:19]
  wire [31:0] _idu_io_out_bits_src1;	// @[src/main/NPC.scala:34:19]
  wire [31:0] _idu_io_out_bits_src2;	// @[src/main/NPC.scala:34:19]
  wire [31:0] _idu_io_out_bits_src3;	// @[src/main/NPC.scala:34:19]
  wire        _idu_io_out_bits_wen;	// @[src/main/NPC.scala:34:19]
  wire [3:0]  _idu_io_out_bits_rd;	// @[src/main/NPC.scala:34:19]
  wire [2:0]  _idu_io_out_bits_decode_funct3;	// @[src/main/NPC.scala:34:19]
  wire        _idu_io_out_bits_decode_isLoad;	// @[src/main/NPC.scala:34:19]
  wire        _idu_io_out_bits_decode_isStore;	// @[src/main/NPC.scala:34:19]
  wire        _idu_io_out_bits_decode_isJmp;	// @[src/main/NPC.scala:34:19]
  wire [31:0] _idu_io_out_bits_snpc;	// @[src/main/NPC.scala:34:19]
  wire [31:0] _ifu_io_mem_pc;	// @[src/main/NPC.scala:33:19]
  wire        _ifu_io_mem_pcValid;	// @[src/main/NPC.scala:33:19]
  wire        _ifu_io_out_valid;	// @[src/main/NPC.scala:33:19]
  wire [31:0] _ifu_io_out_bits_inst;	// @[src/main/NPC.scala:33:19]
  wire [31:0] _ifu_io_out_bits_snpc;	// @[src/main/NPC.scala:33:19]
  IFU ifu (	// @[src/main/NPC.scala:33:19]
    .clock             (clock),
    .reset             (reset),
    .io_mem_pc         (_ifu_io_mem_pc),
    .io_mem_pcValid    (_ifu_io_mem_pcValid),
    .io_mem_inst       (_bridge_io_ifu_inst),	// @[src/main/NPC.scala:54:24]
    .io_mem_instValid  (_bridge_io_ifu_instValid),	// @[src/main/NPC.scala:54:24]
    .io_out_valid      (_ifu_io_out_valid),
    .io_out_bits_inst  (_ifu_io_out_bits_inst),
    .io_out_bits_snpc  (_ifu_io_out_bits_snpc),
    .io_redirect_valid (_exu_io_redirect_valid),	// @[src/main/NPC.scala:35:19]
    .io_redirect_dnpc  (_exu_io_redirect_dnpc),	// @[src/main/NPC.scala:35:19]
    .io_nextInst       (_lsu_io_out_valid)	// @[src/main/NPC.scala:36:19]
  );	// @[src/main/NPC.scala:33:19]
  IDU idu (	// @[src/main/NPC.scala:34:19]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_valid                (_ifu_io_out_valid),	// @[src/main/NPC.scala:33:19]
    .io_in_bits_inst            (_ifu_io_out_bits_inst),	// @[src/main/NPC.scala:33:19]
    .io_in_bits_snpc            (_ifu_io_out_bits_snpc),	// @[src/main/NPC.scala:33:19]
    .io_out_valid               (_idu_io_out_valid),
    .io_out_bits_src1           (_idu_io_out_bits_src1),
    .io_out_bits_src2           (_idu_io_out_bits_src2),
    .io_out_bits_src3           (_idu_io_out_bits_src3),
    .io_out_bits_wen            (_idu_io_out_bits_wen),
    .io_out_bits_rd             (_idu_io_out_bits_rd),
    .io_out_bits_decode_funct3  (_idu_io_out_bits_decode_funct3),
    .io_out_bits_decode_isLoad  (_idu_io_out_bits_decode_isLoad),
    .io_out_bits_decode_isStore (_idu_io_out_bits_decode_isStore),
    .io_out_bits_decode_isJmp   (_idu_io_out_bits_decode_isJmp),
    .io_out_bits_snpc           (_idu_io_out_bits_snpc),
    .io_wb_res                  (_wbu_io_wb_res),	// @[src/main/NPC.scala:37:19]
    .io_wb_wen                  (_wbu_io_wb_wen),	// @[src/main/NPC.scala:37:19]
    .io_wb_rd                   (_wbu_io_wb_rd)	// @[src/main/NPC.scala:37:19]
  );	// @[src/main/NPC.scala:34:19]
  EXU exu (	// @[src/main/NPC.scala:35:19]
    .io_in_valid                (_idu_io_out_valid),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_src1            (_idu_io_out_bits_src1),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_src2            (_idu_io_out_bits_src2),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_src3            (_idu_io_out_bits_src3),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_wen             (_idu_io_out_bits_wen),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_rd              (_idu_io_out_bits_rd),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_decode_funct3   (_idu_io_out_bits_decode_funct3),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_decode_isLoad   (_idu_io_out_bits_decode_isLoad),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_decode_isStore  (_idu_io_out_bits_decode_isStore),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_decode_isJmp    (_idu_io_out_bits_decode_isJmp),	// @[src/main/NPC.scala:34:19]
    .io_in_bits_snpc            (_idu_io_out_bits_snpc),	// @[src/main/NPC.scala:34:19]
    .io_out_valid               (_exu_io_out_valid),
    .io_out_bits_res            (_exu_io_out_bits_res),
    .io_out_bits_wen            (_exu_io_out_bits_wen),
    .io_out_bits_rd             (_exu_io_out_bits_rd),
    .io_out_bits_wdata          (_exu_io_out_bits_wdata),
    .io_out_bits_wmask          (_exu_io_out_bits_wmask),
    .io_out_bits_decode_funct3  (_exu_io_out_bits_decode_funct3),
    .io_out_bits_decode_isLoad  (_exu_io_out_bits_decode_isLoad),
    .io_out_bits_decode_isStore (_exu_io_out_bits_decode_isStore),
    .io_out_bits_decode_isJmp   (_exu_io_out_bits_decode_isJmp),
    .io_out_bits_snpc           (_exu_io_out_bits_snpc),
    .io_redirect_valid          (_exu_io_redirect_valid),
    .io_redirect_dnpc           (_exu_io_redirect_dnpc)
  );	// @[src/main/NPC.scala:35:19]
  LSU lsu (	// @[src/main/NPC.scala:36:19]
    .clock                     (clock),
    .reset                     (reset),
    .io_mem_reqValid           (_lsu_io_mem_reqValid),
    .io_mem_addr               (_lsu_io_mem_addr),
    .io_mem_size               (_lsu_io_mem_size),
    .io_mem_respValid          (_bridge_io_lsu_respValid),	// @[src/main/NPC.scala:54:24]
    .io_mem_rdata              (_bridge_io_lsu_rdata),	// @[src/main/NPC.scala:54:24]
    .io_mem_wen                (_lsu_io_mem_wen),
    .io_mem_wdata              (_lsu_io_mem_wdata),
    .io_mem_wmask              (_lsu_io_mem_wmask),
    .io_in_valid               (_exu_io_out_valid),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_res            (_exu_io_out_bits_res),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_wen            (_exu_io_out_bits_wen),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_rd             (_exu_io_out_bits_rd),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_wdata          (_exu_io_out_bits_wdata),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_wmask          (_exu_io_out_bits_wmask),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_decode_funct3  (_exu_io_out_bits_decode_funct3),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_decode_isLoad  (_exu_io_out_bits_decode_isLoad),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_decode_isStore (_exu_io_out_bits_decode_isStore),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_decode_isJmp   (_exu_io_out_bits_decode_isJmp),	// @[src/main/NPC.scala:35:19]
    .io_in_bits_snpc           (_exu_io_out_bits_snpc),	// @[src/main/NPC.scala:35:19]
    .io_out_valid              (_lsu_io_out_valid),
    .io_out_bits_res           (_lsu_io_out_bits_res),
    .io_out_bits_wen           (_lsu_io_out_bits_wen),
    .io_out_bits_rd            (_lsu_io_out_bits_rd)
  );	// @[src/main/NPC.scala:36:19]
  WBU wbu (	// @[src/main/NPC.scala:37:19]
    .io_in_valid    (_lsu_io_out_valid),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_res (_lsu_io_out_bits_res),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_wen (_lsu_io_out_bits_wen),	// @[src/main/NPC.scala:36:19]
    .io_in_bits_rd  (_lsu_io_out_bits_rd),	// @[src/main/NPC.scala:36:19]
    .io_wb_res      (_wbu_io_wb_res),
    .io_wb_wen      (_wbu_io_wb_wen),
    .io_wb_rd       (_wbu_io_wb_rd)
  );	// @[src/main/NPC.scala:37:19]
  MemBridge bridge (	// @[src/main/NPC.scala:54:24]
    .clock               (clock),
    .reset               (reset),
    .io_ifu_pc           (_ifu_io_mem_pc),	// @[src/main/NPC.scala:33:19]
    .io_ifu_pcValid      (_ifu_io_mem_pcValid),	// @[src/main/NPC.scala:33:19]
    .io_ifu_inst         (_bridge_io_ifu_inst),
    .io_ifu_instValid    (_bridge_io_ifu_instValid),
    .io_lsu_reqValid     (_lsu_io_mem_reqValid),	// @[src/main/NPC.scala:36:19]
    .io_lsu_addr         (_lsu_io_mem_addr),	// @[src/main/NPC.scala:36:19]
    .io_lsu_size         (_lsu_io_mem_size),	// @[src/main/NPC.scala:36:19]
    .io_lsu_respValid    (_bridge_io_lsu_respValid),
    .io_lsu_rdata        (_bridge_io_lsu_rdata),
    .io_lsu_wen          (_lsu_io_mem_wen),	// @[src/main/NPC.scala:36:19]
    .io_lsu_wdata        (_lsu_io_mem_wdata),	// @[src/main/NPC.scala:36:19]
    .io_lsu_wmask        (_lsu_io_mem_wmask),	// @[src/main/NPC.scala:36:19]
    .io_out_awready     (io_master_awready),
    .io_out_awvalid     (io_master_awvalid),
    .io_out_awaddr (io_master_awaddr),
    .io_out_awsize (io_master_awsize),
    .io_out_wready      (io_master_wready),
    .io_out_wvalid      (io_master_wvalid),
    .io_out_wdata  (io_master_wdata),
    .io_out_wstrb  (io_master_wstrb),
    .io_out_bready      (io_master_bready),
    .io_out_bvalid      (io_master_bvalid),
    .io_out_arready     (io_master_arready),
    .io_out_arvalid     (io_master_arvalid),
    .io_out_araddr (io_master_araddr),
    .io_out_arsize (io_master_arsize),
    .io_out_rready      (io_master_rready),
    .io_out_rvalid      (io_master_rvalid),
    .io_out_rdata  (io_master_rdata)
  );	// @[src/main/NPC.scala:54:24]
endmodule

module Top(	// @[src/main/NPC.scala:67:7]
  input         clock,	// @[src/main/NPC.scala:67:7]
                reset,	// @[src/main/NPC.scala:67:7]
                io_master_awready,	// @[src/main/NPC.scala:68:14]
  output        io_master_awvalid,	// @[src/main/NPC.scala:68:14]
  output [31:0] io_master_awaddr,	// @[src/main/NPC.scala:68:14]
  output [2:0]  io_master_awsize,	// @[src/main/NPC.scala:68:14]
  output [3:0]  io_master_awid,	// @[src/main/NPC.scala:68:14]
  output [7:0]  io_master_awlen,	// @[src/main/NPC.scala:68:14]
  output [1:0]  io_master_awburst,	// @[src/main/NPC.scala:68:14]
  input         io_master_wready,	// @[src/main/NPC.scala:68:14]
  output        io_master_wvalid,	// @[src/main/NPC.scala:68:14]
  output [31:0] io_master_wdata,	// @[src/main/NPC.scala:68:14]
  output [3:0]  io_master_wstrb,	// @[src/main/NPC.scala:68:14]
  output        io_master_wlast,	// @[src/main/NPC.scala:68:14]
                io_master_bready,	// @[src/main/NPC.scala:68:14]
  input         io_master_bvalid,	// @[src/main/NPC.scala:68:14]
  input  [1:0]  io_master_bresp,	// @[src/main/NPC.scala:68:14]
  input  [3:0]  io_master_bid,	// @[src/main/NPC.scala:68:14]
  input         io_master_arready,	// @[src/main/NPC.scala:68:14]
  output        io_master_arvalid,	// @[src/main/NPC.scala:68:14]
  output [31:0] io_master_araddr,	// @[src/main/NPC.scala:68:14]
  output [2:0]  io_master_arsize,	// @[src/main/NPC.scala:68:14]
  output [3:0]  io_master_arid,	// @[src/main/NPC.scala:68:14]
  output [7:0]  io_master_arlen,	// @[src/main/NPC.scala:68:14]
  output [1:0]  io_master_arburst,	// @[src/main/NPC.scala:68:14]
  output        io_master_rready,	// @[src/main/NPC.scala:68:14]
  input         io_master_rvalid,	// @[src/main/NPC.scala:68:14]
  input  [1:0]  io_master_rresp,	// @[src/main/NPC.scala:68:14]
  input  [31:0] io_master_rdata,	// @[src/main/NPC.scala:68:14]
  input         io_master_rlast,	// @[src/main/NPC.scala:68:14]
  input  [3:0]  io_master_rid,	// @[src/main/NPC.scala:68:14]
  input         io_interrupt,	// @[src/main/NPC.scala:68:14]
  output        io_slave_awready,	// @[src/main/NPC.scala:68:14]
  input         io_slave_awvalid,	// @[src/main/NPC.scala:68:14]
  input  [31:0] io_slave_awaddr,	// @[src/main/NPC.scala:68:14]
  input  [2:0]  io_slave_awsize,	// @[src/main/NPC.scala:68:14]
  input  [3:0]  io_slave_awid,	// @[src/main/NPC.scala:68:14]
  input  [7:0]  io_slave_awlen,	// @[src/main/NPC.scala:68:14]
  input  [1:0]  io_slave_awburst,	// @[src/main/NPC.scala:68:14]
  output        io_slave_wready,	// @[src/main/NPC.scala:68:14]
  input         io_slave_wvalid,	// @[src/main/NPC.scala:68:14]
  input  [31:0] io_slave_wdata,	// @[src/main/NPC.scala:68:14]
  input  [3:0]  io_slave_wstrb,	// @[src/main/NPC.scala:68:14]
  input         io_slave_wlast,	// @[src/main/NPC.scala:68:14]
                io_slave_bready,	// @[src/main/NPC.scala:68:14]
  output        io_slave_bvalid,	// @[src/main/NPC.scala:68:14]
  output [1:0]  io_slave_bresp,	// @[src/main/NPC.scala:68:14]
  output [3:0]  io_slave_bid,	// @[src/main/NPC.scala:68:14]
  output        io_slave_arready,	// @[src/main/NPC.scala:68:14]
  input         io_slave_arvalid,	// @[src/main/NPC.scala:68:14]
  input  [31:0] io_slave_araddr,	// @[src/main/NPC.scala:68:14]
  input  [2:0]  io_slave_arsize,	// @[src/main/NPC.scala:68:14]
  input  [3:0]  io_slave_arid,	// @[src/main/NPC.scala:68:14]
  input  [7:0]  io_slave_arlen,	// @[src/main/NPC.scala:68:14]
  input  [1:0]  io_slave_arburst,	// @[src/main/NPC.scala:68:14]
  input         io_slave_rready,	// @[src/main/NPC.scala:68:14]
  output        io_slave_rvalid,	// @[src/main/NPC.scala:68:14]
  output [1:0]  io_slave_rresp,	// @[src/main/NPC.scala:68:14]
  output [31:0] io_slave_rdata,	// @[src/main/NPC.scala:68:14]
  output        io_slave_rlast,	// @[src/main/NPC.scala:68:14]
  output [3:0]  io_slave_rid	// @[src/main/NPC.scala:68:14]
);

  NPC npc (	// @[src/main/NPC.scala:74:19]
    .clock                  (clock),
    .reset                  (reset),
    .io_master_awready     (io_master_awready),
    .io_master_awvalid     (io_master_awvalid),
    .io_master_awaddr (io_master_awaddr),
    .io_master_awsize (io_master_awsize),
    .io_master_wready      (io_master_wready),
    .io_master_wvalid      (io_master_wvalid),
    .io_master_wdata  (io_master_wdata),
    .io_master_wstrb  (io_master_wstrb),
    .io_master_bready      (io_master_bready),
    .io_master_bvalid      (io_master_bvalid),
    .io_master_arready     (io_master_arready),
    .io_master_arvalid     (io_master_arvalid),
    .io_master_araddr (io_master_araddr),
    .io_master_arsize (io_master_arsize),
    .io_master_rready      (io_master_rready),
    .io_master_rvalid      (io_master_rvalid),
    .io_master_rdata  (io_master_rdata)
  );	// @[src/main/NPC.scala:74:19]
  assign io_master_awid = 4'h0;	// @[src/main/NPC.scala:67:7]
  assign io_master_awlen = 8'h0;	// @[src/main/NPC.scala:67:7, :74:19]
  assign io_master_awburst = 2'h0;	// @[src/main/NPC.scala:67:7]
  assign io_master_wlast = 1'h1;	// @[src/main/NPC.scala:67:7, :74:19]
  assign io_master_arid = 4'h0;	// @[src/main/NPC.scala:67:7]
  assign io_master_arlen = 8'h0;	// @[src/main/NPC.scala:67:7, :74:19]
  assign io_master_arburst = 2'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_awready = 1'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_wready = 1'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_bvalid = 1'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_bresp = 2'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_bid = 4'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_arready = 1'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_rvalid = 1'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_rresp = 2'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_rdata = 32'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_rlast = 1'h0;	// @[src/main/NPC.scala:67:7]
  assign io_slave_rid = 4'h0;	// @[src/main/NPC.scala:67:7]
endmodule

